### PR TITLE
Update to 1.23.0

### PR DESCRIPTION
**Pull request by wbadart**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
  - Was already `0`
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wbadart** [comment]
@conda-forge-admin, please rerender

**Review by proinsias — APPROVED** [review]

**Comment by bollwyvl** [comment]
Thanks!

We should add pip check to the test section.

Weird that it wasn't updated earlier by the bot... Probably need to clean
up the syntax to be more normal (since it still can't lint itself)...

**Comment by bollwyvl** [comment]
@wbadart merged this in via #23: should be available within 30 minutes on CDN!

**Comment by wbadart** [comment]
Fantastic. Really appreciate the quick turnaround!

**Pull request merged**
